branches:
  only:
    - master
image:
  - Visual Studio 2019
  - Ubuntu2004
  - macOS

environment:
  matrix:
    - nodejs_version: 21
    - nodejs_version: 20
    - nodejs_version: 19
    - nodejs_version: 18
    - nodejs_version: 17
    - nodejs_version: 16
    - nodejs_version: 15
    - nodejs_version: 14
    - nodejs_version: 13
    - nodejs_version: 12
    - nodejs_version: 11
    - nodejs_version: 10

for:
  - matrix:
      only:
        - image: Visual Studio 2019
    init:
      - git config --global core.autocrlf true
    install:
      - ps: Install-Product node $env:nodejs_version
    test_script:
      - node --version
      - npm --version
      - npm run testminimal

  - matrix:
      only:
        - image: macOS
    install:
      - nvm install $nodejs_version
      - nvm use $nodejs_version
    test_script:
      - node --version
      - npm --version
      - npm run testminimal

  - matrix:
      only:
        - image: Ubuntu2004
    install:
      - nvm use $nodejs_version
    test_script:
      - node --version
      - npm --version
      - if [[ ${nodejs_version} != 16 ]]; then npm run test; fi;
      - if [[ ${nodejs_version} == 16 ]]; then npm run coverage; npx codecov; fi;

build: false
