init:
  - git config --global core.autocrlf true

environment:
  matrix:
    - nodejs_version: "13"
    - nodejs_version: "12"
    - nodejs_version: "11"
    - nodejs_version: "10"
    - nodejs_version: "8"
    - nodejs_version: "7"
    - nodejs_version: "6"
    - nodejs_version: "5"
    - nodejs_version: "4"

platform:
  - x86
  - x64

install:
  - ps: Install-Product node $env:nodejs_version

build: off

test_script:
  - node --version
  - npm --version
  - npm test

